spring.application.name=e-commerce-api

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

JWT.SECRET=${JWT_SECRET}

cloudflare.r2.access-key=${R2_ACCESS_KEY}
cloudflare.r2.secret-key=${R2_SECRET_KEY}
cloudflare.r2.bucket-name=ecommerce-bucket
cloudflare.r2.endpoint=${R2_ENDPOINT}
cloudflare.r2.region=${R2_REGION}